add .github and test to npmignore
ljharb/es-abstract pull request #123
Opened 2020-12-24 03:34 UTC by david-fong

Similar changes can be made to the dependencies of this package that you also maintain.

Fixes #122

2020-12-24 03:56 UTC, ljharb requested changes

2020-12-24 03:56 UTC, ljharb commented on .npmignore
> +.github
this is fine, but negligible

2020-12-24 03:56 UTC, ljharb commented on .npmignore
> +test/
this is intentional - `npm explore foo && npm install && npm test` should work for all packages.

2020-12-24 04:21 UTC, ljharb approved these changes
Seems pretty valueless, but now it doesn't hurt at least.

2021-01-05 19:20 UTC, ljharb commented
@david-fong it's very unfortunate you deleted your fork :-/ that's an unrecoverable action that prevents me from making further changes or rebasing.

2021-01-05 19:21 UTC, merged

2021-01-06 01:52 UTC, david-fong commented
@ljharb I'm super sorry I did that! I wasn't using my brain enough when I was deleting some of my forks :( I'll make sure not to delete forks with open PR's in the future. Again, sorry, and thank you so much for taking a look at this little PR. Happy new year!

2021-01-06 03:20 UTC, ljharb commented
No worries, thanks for the contribution :-)