fix: folder mapping deprecation warning (#133)
ljharb/es-abstract pull request #134
Opened 2021-07-30 11:42 UTC by coderaiser

Fixed deprecation warning:
![image](https://user-images.githubusercontent.com/1573141/127648091-20eed460-f9fa-4c8a-9607-b3c79dd92538.png)

2021-07-30 15:38 UTC, varwasabi commented
Can confirm that this change fixes the message from showing.

2021-07-30 16:00 UTC, ljharb requested changes
This is a breaking change; it will break consumers like https://github.com/es-shims/Array.prototype.at/blob/main/index.mjs#L2, and any users on node 12.17 (or any other node that understands "exports" but not subpath patterns)

2021-08-01 15:40 UTC, coderaiser commented
Updated to get `node v12` and `node v16` supported according to workaround https://github.com/nodejs/node/issues/38353#issuecomment-825221607

2021-08-02 00:01 UTC, ljharb commented on package.json
> +		"./*": "./*.js"
unfortunately, this causes ` Cannot find module '$PWD/node_modules/es-abstract/2020/RequireObjectCoercible.js.js'` or similar in node 16.6, 12.23, and 12.17 when I try to import with the extension - when i try to import without the extension, I get `Cannot find module '$PWD/node_modules/es-abstract/2020/RequireObjectCoercible'` in node v12.17 - so this doesn't suffice.

If you remove the `.js` from all the RHS's of these lines, then ESM works, but CJS (the vastly more important consumer for the foreseeable future) is no longer able to require them without extensions.

2021-08-02 07:23 UTC, coderaiser commented
Closed due to removed `exports`.

2021-08-02 07:23 UTC, closed without merging